# For development
# - volume mount app folders to container.
# - requires rebuilding containers when changing dependencies.
#
# usage:
# (sudo) docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d
# (sudo) docker-compose -f docker-compose.yml -f docker-compose.dev.yml down
services: 

  frontend:
    environment:
      - FLASK_ENV=development 
      - API_INTERNAL_URL=http://api:8000
      - API_EXTERNAL_URL=http://localhost:8001
    depends_on:
      - api
    command: "flask run --reload --debug --host 0.0.0.0"


  api:
    environment: 
      - notification_service_api=http://notification_service:8000/
    build: 
      target: development
    develop:
      watch: 
        - path: ./api/setup.cfg
          action: rebuild
        - path: ./api/bonsai_api
          target: /app/bonsai_api/bonsai_api
          action: sync
        - path: ./libs/api_client/pyproject.toml
          action: rebuild
        - path: ./libs/api_client/api_client
          target: /app/api_client/api_client
          action: sync
    command: "uvicorn bonsai_api.main:app --reload --log-level info --host 0.0.0.0"

  minhash_service:
    build: 
      target: development
    develop:
      watch: 
        - path: ./minhash_service/pyproject.toml
          action: rebuild
        - path: ./minhash_service/minhash_service
          target: /app/minhash_service/minhash_service
          action: sync
        - path: ./libs/api_client/pyproject.toml
          action: rebuild
        - path: ./libs/api_client/api_client
          target: /app/api_client/api_client
          action: sync

  minhash_cron_service:
    environment:
      - INTEGRITY_TASK_CRON=* * * * *
      - PURGE_FILES_TASK_CRON=* * * * *
    build: 
      target: development
    develop:
      watch: 
        - path: ./minhash_service/pyproject.toml
          action: rebuild
        - path: ./minhash_service/minhash_service
          target: /app/minhash_service/minhash_service
          action: sync
        - path: ./libs/api_client/pyproject.toml
          action: rebuild
        - path: ./libs/api_client/api_client
          target: /app/api_client/api_client
          action: sync
  
  allele_cluster_service:
    build: 
      target: development
    develop:
      watch: 
        - path: ./allele_cluster_service/setup.cfg
          action: rebuild
        - path: ./allele_cluster_service/allele_cluster_service
          target: /app/allele_cluster_service/allele_cluster_service
          action: sync

  notification_service:
    environment:
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
    depends_on:
      - mailhog

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - bonsai-net