# For development
# - volume mount app folders to container.
# - requires rebuilding containers when changing dependencies.
#
# usage:
# (sudo) docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d
# (sudo) docker-compose -f docker-compose.yml -f docker-compose.dev.yml down
services: 

  api:
    build: 
      target: development
    develop:
      watch: 
        - path: ./api/setup.cfg
          action: rebuild
        - path: ./api/bonsai_api
          target: /app/bonsai_api/bonsai_api
          action: sync
        - path: ./libs/api_client/pyproject.toml
          action: rebuild
        - path: ./libs/api_client/api_client
          target: /app/api_client/api_client
          action: sync

  minhash_service:
    build: 
      target: development
    develop:
      watch: 
        - path: ./minhash_service/pyproject.toml
          action: rebuild
        - path: ./minhash_service/minhash_service
          target: /app/minhash_service/minhash_service
          action: sync
        - path: ./libs/api_client/pyproject.toml
          action: rebuild
        - path: ./libs/api_client/api_client
          target: /app/api_client/api_client
          action: sync

  minhash_cron_service:
    environment:
      - INTEGRITY_TASK_CRON=* * * * *
      - PURGE_FILES_TASK_CRON=* * * * *
    build: 
      target: development
    develop:
      watch: 
        - path: ./minhash_service/pyproject.toml
          action: rebuild
        - path: ./minhash_service/minhash_service
          target: /app/minhash_service/minhash_service
          action: sync
        - path: ./libs/api_client/pyproject.toml
          action: rebuild
        - path: ./libs/api_client/api_client
          target: /app/api_client/api_client
          action: sync
