# run e2e tests by overriding the existing compose file:
# (sudo) docker-compose -f docker-compose.yml -f docker-compose.e2e_tests.yml run
services:
  chrome:
    container_name: chrome
    hostname: chrome
    image: selenium/standalone-chrome
    platform: linux/x86_64
    shm_size: 2gb
    privileged: true
    ports:
     - "4444:4444"
     - "7900:7900"
    restart: allways
    networks:
     - bonsai-net

  e2e-tests:
    container_name: e2e-tests
    build: 
      context: e2e_tests
      network: host
    volumes:
     - ./scripts/upload_sample.py:/app/upload_sample.py
     - ./reports/:/app/reports:rw
    depends_on:
      chrome:
        condition: service_started
      frontend:
        condition: service_started
      api:
        condition: service_healthy
    restart: no
    networks:
     - bonsai-net
    
  smoke-data:
    image: clinicalgenomicslund/bonsai-prp:dev
    depends_on:
      bootstrap:
        condition: service_completed_successfully
    environment:
      - API_URL=http://api:8000
    volumes:
      - ./e2e_tests/fixture/smoke:/data
    command: "prp bonsai upload /data/tb_sample_1/tb_sample_1.manifest.yml"
    restart: no
    env_file: docker-compose.env
    networks:
      - bonsai-net