"""Analysis related data models"""

from datetime import datetime
from pydantic import Field
from .base import ForbidExtraModelMixin, AllowExtraModelMixin


class PipelineArtifact(ForbidExtraModelMixin):
    """Describe a file generated by the pipeline."""

    software_name: str
    software_version: str
    uri: str


class PipelineProvenance(AllowExtraModelMixin):
    """Evidence of what was executed.
    
    Includes configfiles, hashes, traces etc."""

    configuration_files: list[str]
    environment: dict[str, str]
    reports: dict[str, str]


class PipelineInfo(AllowExtraModelMixin):
    """Describe what pipeline was executed and its configuration."""

    pipeline_name: str
    pipeline_version: str
    commit: str
    release_life_cycle: str
    commmand: str
    analysis_profile: list[str]
    provenance: PipelineProvenance
    artifacts: list[PipelineArtifact] = Field(default_factory=list)


class PipelineRun(AllowExtraModelMixin):
    """Describe a execution of a pipeline."""

    sample_id: str
    pipeline_run_id: str
    executed_at: datetime
    assay: str
    pipeline_info: PipelineInfo