"""Analysis-related data models.

Include models for describing a pipeline execution and analysis results.
"""
from enum import StrEnum
from datetime import datetime
from typing import Any, Dict, List, Optional, Sequence

from pydantic import BaseModel, Field, ConfigDict

from bonsai_api.models.base import AllowExtraModelMixin, ForbidExtraModelMixin, Timestamps


class AnalysisType(StrEnum):
    AMR = "amr"
    VIRULENCE = "virulence"
    TYPING = "typing"
    QC = "qc"
    ALIGNMENT = "alignment"
    OTHER = "other"


class TargetType(StrEnum):
    VARIANT = "variant"
    GENE = "gene"
    OTHER = "other"


class PipelineArtifact(ForbidExtraModelMixin):
    """Describe a file generated by the pipeline."""

    software_name: str
    software_version: str
    uri: str


class PipelineProvenance(AllowExtraModelMixin):
    """Evidence of what was executed.
    
    Includes configfiles, hashes, traces etc."""

    configuration_files: list[str]
    environment: dict[str, str]
    reports: dict[str, str]


class PipelineInfo(AllowExtraModelMixin):
    """Describe what pipeline was executed and its configuration."""

    pipeline_name: str
    pipeline_version: str
    commit: str
    release_life_cycle: str
    commmand: str
    analysis_profile: list[str]
    provenance: PipelineProvenance
    artifacts: list[PipelineArtifact] = Field(default_factory=list)


class PipelineRun(AllowExtraModelMixin):
    """Describe a execution of a pipeline."""

    sample_id: str
    pipeline_run_id: str
    executed_at: datetime
    assay: str
    pipeline_info: PipelineInfo


class AnalysisResult(Timestamps, AllowExtraModelMixin):
    """Container of analysis results."""

    sample_id: str
    analysis_type: AnalysisType
    software: str
    software_version: str | None = None
    parser_version: str | None = None
    analysis_run_id: str | None = None

    result_raw: dict[str, Any] = Field(default_factory=dict)
    result_parsed: dict[str, Any] | None = None
    result_curated: dict[str, Any] | None = None

    notes: str | None = None


class Curation(Timestamps, AllowExtraModelMixin):
    """Overlay currated results."""

    analysis_id: str
    sample_id: str
    target_type: TargetType
    target_id: str
    json_patch: Optional[Sequence[Dict[str, Any]]] = None
    delta: Optional[Dict[str, Any]] = None
    author: str
    reason: Optional[str] = None
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    reverted: bool = False
    applied_at: Optional[datetime] = None
    applied_by: Optional[str] = None
    acknowledged_export: bool = False


class MetadataEntry(BaseModel):
    model_config = ConfigDict(extra="allow")

    key: str
    value: Any
    source: Optional[str] = None
    created_at: Optional[datetime] = None


class SequencingInfo(ForbidExtraModelMixin):
    """Information on the sample was sequenced."""

    run_id: str
    platform: str
    instrument: str | None = None
    method: dict[str, str] = Field(default_factory=dict)
    date: datetime | None = None
