"""Analysis related data models"""

from datetime import datetime
from pydantic import BaseModel, Field
from .base import ForbidExtraModelMixin, AllowExtraModelMixin

class PipelineArtifact(BaseModel):
    """Describe a file generated by the pipeline."""

    software_name: str
    software_version: str
    uri: str


class PipelineDefinition(BaseModel):
    """Static metadata about the pipeline code itself."""

    name: str
    version: str
    commit: str | None = None
    release_life_cycle: str | None = None


class PipelineRunConfig(BaseModel):
    """Configuration used for this specific execution."""

    command: str
    analysis_profile: list[str] = Field(default_factory=list)
    configuration_files: list[str] = Field(default_factory=list)


class PipelineInfo(BaseModel):
    """Full description of the pipeline and its execution."""

    definition: PipelineDefinition
    run_config: PipelineRunConfig
    artifacts: list[PipelineArtifact] = Field(default_factory=list)


class PipelineRun(ForbidExtraModelMixin):
    """Describe a execution of a pipeline."""

    pipeline_run_id: str
    executed_at: datetime
    assay: str
    pipeline_info: PipelineInfo
