[species.bracken.staphylococcus_aureus]
min_fraction = 0.6
min_reads = 10000

[species.bracken.escherichia_coli]
min_fraction = 0.6
min_reads = 10000

[species.bracken.klebsiella_pneumoniae]
min_fraction = 0.6
min_reads = 10000

[species.bracken.mycobacterium_tuberculosis]
min_fraction = 0.6
min_reads = 10000

[species.bracken.default]
min_fraction = 0.9
min_reads = 10000

[species.mykrobe.mycobacterium_tuberculosis]
min_species_coverage = 0.95
min_phylogenetic_group_coverage = 0.95

[species.mykrobe.default]
min_species_coverage = 1
min_phylogenetic_group_coverage = 1